### ISSUE TITLE
Add CITATION.cff file

### ISSUE THREAD

**Issue by meliache** [b2-hive/eFFORT#22]
This would enable the citation  in github, see this tweet by the twitter CEO: https://twitter.com/natfriedman/status/1420122675813441540 and the homepage of the citation file format: https://citation-file-format.github.io/.

For example:

``` yaml
cff-version: 1.1.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Prim
    given-names: Markus Tobias
    orcid: https://orcid.org/0000-0002-1407-7450
title: "b2-hive/eFFORT"
version: 0.1.0 
doi: 10.5281/zenodo.3965698
date-released: 2017-12-18
```
